name: "Java CI"
on:
  push:
    branches:
      - '[3-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[3-9]+.[0-9]+.x'
  workflow_dispatch:
permissions:
  packages: read
jobs:
  test_project:
    name: "Test Project"
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🏃‍♂️ Run Tests"
        run: ./gradlew check --continue
  publish_snapshot:
    name: "Build Project and Publish Snapshot"
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "📤 Publish Snapshot artifacts"
        env:
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW }}
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
        run: ./gradlew --no-build-cache publish
      - name: "🔨 Generate Snapshot Documentation"
        run: ./gradlew docs
      - name: "🚀 Publish to Github Pages"
        uses: apache/grails-github-actions/deploy-github-pages@asf
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_RELEASE: 'false'
          SOURCE_FOLDER: build/docs/manual
